# Generated by Django 4.0.4 on 2022-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_category_courses_orders_coursesvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
