# Generated by Django 4.0.4 on 2022-05-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teachermodel_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_number', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='orders',
            name='check_number',
        ),
        migrations.AddField(
            model_name='orders',
            name='check_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.check'),
            preserve_default=False,
        ),
    ]
