# Generated by Django 4.0.4 on 2022-05-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_check_remove_orders_check_number_orders_check_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='check_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='check_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='pay',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Check',
        ),
    ]
